services:
  - type: web
    name: luchik-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "False"
      - key: POSTGRES_HOST
        fromDatabase:
          name: luchik-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: luchik-db
          property: port
      - key: POSTGRES_DB
        fromDatabase:
          name: luchik-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: luchik-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: luchik-db
          property: password
      - key: ALLOWED_HOSTS
        value: luchik-backend.onrender.com
    healthCheckPath: /api/home/

  - type: web
    name: luchik-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://luchik-backend.onrender.com

databases:
  - name: luchik-db
    databaseName: luchik
    user: luchik
    plan: free

